services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5005"
    ports:
      - "5005:5005"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - nginx_proxy

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - nginx_proxy

volumes:
  npm_data:
  npm_letsencrypt:

networks:
  nginx_proxy:
    driver: bridge
